'use client';import {useEffect,useState} from 'react';
export default function Settings(){const [s,setS]=useState<any>();const [msg,setMsg]=useState('');const [uploading,setUploading]=useState<string>('');useEffect(()=>{fetch('/api/settings').then(r=>r.json()).then(setS)},[]);if(!s)return <div>লোড হচ্ছে...</div>;const set=(k:string,v:any)=>setS((x:any)=>({...x,[k]:v}));async function save(e:any){e.preventDefault();const r=await fetch('/api/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(s)});setMsg(r.ok?'Settings saved ✓':'Save failed')}async function upload(k:string,e:any){
 const f=e.target.files?.[0]; if(!f)return;
 setUploading(k); setMsg('');
 const fd=new FormData(); fd.append('file',f);
 try{
  const r=await fetch('/api/upload',{method:'POST',body:fd});
  const d=await r.json();
  if(!r.ok) throw new Error(d.error||'Upload failed');
  set(k,d.url); setMsg((k==='logo'?'Logo':'Banner')+' upload হয়েছে ✓');
 }catch(x:any){setMsg(x.message||'Upload failed')}finally{setUploading('')}
}return <><div className="adminTop"><div><h1>Store & Homepage Settings</h1><p>দোকানের পরিচিতি, যোগাযোগ ও Homepage-এর লেখা পরিবর্তন করুন।</p></div></div><form className="adminForm" onSubmit={save}><h2>Store Information</h2><div className="formGrid"><label>Store Name<input value={s.storeName||''} onChange={e=>set('storeName',e.target.value)}/></label><label>Phone<input value={s.phone||''} onChange={e=>set('phone',e.target.value)}/></label><label>WhatsApp<input value={s.whatsapp||''} onChange={e=>set('whatsapp',e.target.value)}/></label><label>Email<input value={s.email||''} onChange={e=>set('email',e.target.value)}/></label><label>bKash<input value={s.bkash||''} onChange={e=>set('bkash',e.target.value)}/></label><label>Nagad<input value={s.nagad||''} onChange={e=>set('nagad',e.target.value)}/></label><label>Default Delivery Charge<input type="number" value={s.deliveryCharge||0} onChange={e=>set('deliveryCharge',e.target.value)}/></label><label>Facebook<input value={s.facebook||''} onChange={e=>set('facebook',e.target.value)}/></label></div><div className="formGrid"><label>Logo URL<input value={s.logo||''} onChange={e=>set('logo',e.target.value)}/><input type="file" accept="image/*" onChange={e=>upload('logo',e)}/>{uploading==='logo'?<small>Upload হচ্ছে...</small>:null}{s.logo?<img className="settingsPreview" src={s.logo}/>:null}</label><label>Fallback Banner URL<input value={s.banner||''} onChange={e=>set('banner',e.target.value)}/><input type="file" accept="image/*" onChange={e=>upload('banner',e)}/>{uploading==='banner'?<small>Upload হচ্ছে...</small>:null}{s.banner?<img className="settingsPreview" src={s.banner}/>:null}</label></div><h2>Homepage Content</h2><div className="formGrid"><label>Hero Badge<input value={s.heroBadge||''} onChange={e=>set('heroBadge',e.target.value)}/></label><label>Hero Title<input value={s.heroTitle||''} onChange={e=>set('heroTitle',e.target.value)}/></label></div><label>Hero Subtitle<textarea value={s.heroSubtitle||''} onChange={e=>set('heroSubtitle',e.target.value)}/></label><div className="formGrid"><label>Main Product Section Title<input value={s.productSectionTitle||''} onChange={e=>set('productSectionTitle',e.target.value)}/></label><label>Featured Section Title<input value={s.featuredSectionTitle||''} onChange={e=>set('featuredSectionTitle',e.target.value)}/></label><label>Offer Section Title<input value={s.offerSectionTitle||''} onChange={e=>set('offerSectionTitle',e.target.value)}/></label><label>Footer Text<input value={s.footerText||''} onChange={e=>set('footerText',e.target.value)}/></label></div>{msg?<div className="successMsg">{msg}</div>:null}<button className="primary">Save All Settings</button></form></>}
