import {NextResponse} from 'next/server';import {prisma} from '@/lib/prisma';
export async function GET(){return NextResponse.json(await prisma.order.findMany({include:{customer:true},orderBy:{createdAt:'desc'}}))}
export async function POST(req:Request){const b=await req.json();if(!b.name||!b.phone||!b.address||!b.items?.length)return NextResponse.json({error:'নাম, ফোন, ঠিকানা ও পণ্য প্রয়োজন'},{status:400});
 const ids=b.items.map((i:any)=>Number(i.id));const products=await prisma.product.findMany({where:{id:{in:ids}}});
 let subtotal=0;for(const item of b.items){const p=products.find(x=>x.id===Number(item.id));if(!p||!p.active)return NextResponse.json({error:'একটি পণ্য আর পাওয়া যাচ্ছে না'},{status:400});const qty=Math.max(1,Number(item.qty||1));if(p.stock<qty)return NextResponse.json({error:`${p.name} পর্যাপ্ত স্টকে নেই`},{status:400});subtotal+=p.salePrice*qty}
 const area=b.deliveryAreaId?await prisma.deliveryArea.findUnique({where:{id:Number(b.deliveryAreaId)}}):null;const setting=await prisma.setting.upsert({where:{id:1},update:{},create:{id:1}});const deliveryFee=area?.active?area.charge:Number(setting.deliveryCharge||0);
 const customer=await prisma.customer.create({data:{name:b.name,phone:b.phone,email:b.email||null,address:b.address||null}});const orderNo='SS-'+Date.now().toString().slice(-10);
 const safeItems=b.items.map((item:any)=>{const p=products.find(x=>x.id===Number(item.id))!;return {id:p.id,name:p.name,sku:p.sku,price:p.salePrice,qty:Math.max(1,Number(item.qty||1)),image:p.image||null}});
 const order=await prisma.$transaction(async tx=>{const o=await tx.order.create({data:{orderNo,customerId:customer.id,status:'PENDING',subtotal,deliveryFee,total:subtotal+deliveryFee,paymentMethod:b.paymentMethod||'COD',paymentRef:b.paymentRef||null,deliveryArea:area?.name||null,address:b.address,note:b.note||null,items:JSON.stringify(safeItems)}});for(const item of safeItems)await tx.product.update({where:{id:item.id},data:{stock:{decrement:item.qty}}});return o});return NextResponse.json(order)}
